server:
  port: 8000
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  graphql:
    graphiql:
      enabled: true
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    show-sql: true